const donuts = [
    {
      id: 1,
      name: 'White Frosted Sprinkles',
      filling: 'mit Vanilliecremefüllung',
      topping: 'Zuckerguss mit bunten Zuckerstreuseln',
      price: 2.10,
      img: 'img/classicDonuts/classic-donut1.jpg',
      category: ['classic-donut', 'sweet-donut'],
    },
    {
      id: 2,
      name: 'Chocolate Frosted',
      filling: 'mit Nutella',
      topping: 'dunkle Schokolade und Zuckerguss',
      price: 2.10,
      img: 'img/classicDonuts/classic-donut2.jpg',
      category: ['sweet-donut'],
    },
    {
      id: 3,
      name: 'Lotus Biscoff Ring',
      filling: 'ohne Füllung',
      topping: 'dunkle Schokolade und Schokoplättchen',
      price: 2.10,
      img: 'img/classicDonuts/classic-donut3.jpg',
      category: ['classic-donut', 'sweet-donut'],
    },
    {
      id: 4,
      name: 'Vanilla Frosted',
      filling: 'mit Vanilliecremefüllung',
      topping: 'Zuckerguss und Streuselteig',
      price: 2.50,
      img: 'img/classicDonuts/classic-donut4.jpg',
      category: ['classic-donut', 'sweet-donut'],
    },
    {
      id: 5,
      name: 'Boston Créme',
      filling: 'mit Schokofüllung',
      topping: 'Zartbitterschokolade und bunte Zuckerstreusel',
      price: 2.30,
      img: 'img/sweetDonuts/sweet-donut2.jpg',
      category: ['sweet-donut'],
    },
    {
      id: 6,
      name: 'Oreo Dream',
      filling: 'mit Oreo Creme',
      topping: 'Oreo-Keks',
      price: 3.20,
      img: 'img/sweetDonuts/sweet-donut3.jpg',
      category: ['sweet-donut'],
    },
    {
      id: 7,
      name: 'Strawberry Sprinkle Time',
      filling: 'Erdbeercreme',
      topping: 'bunte Zuckerstreusel',
      price: 1.90,
      img: 'img/sweetDonuts/sweet-donut4.jpg',
      category: ['sweet-donut'],
    },
    {
      id: 8,
      name: 'Fruit Explosion',
      filling: 'ohne Füllung',
      topping: 'Früchte der Saison',
      price: 3.90,
      img: 'img/sweetDonuts/sweet-donut5.jpg',
      category: ['sweet-donut'],
    },
    {
      id: 9,
      name: 'Mr. Dotted',
      filling: 'ohne Füllung',
      topping: 'salziger bunter Puffreis',
      price: 2.90,
      img: 'img/saltyDonuts/donut-salty1.jpg',
      category: ['salty-donut'],
    },
    {
      id: 10,
      name: 'Double salted Chocolate',
      filling: 'Chilli-Schokolade',
      topping: 'Mandelsplitter',
      price: 2.90,
      img: 'img/saltyDonuts/donut-salty2.jpg',
      category: ['salty-donut'],
    },
    {
      id: 11,
      name: 'Salted Glazed',
      filling: 'süße Cremefüllung',
      topping: 'Zucker-Salz-Mischung',
      price: 2.70,
      img: 'img/saltyDonuts/donut-salty3.jpg',
      category: ['salty-donut'],
    },
    {
      id: 12,
      name: 'Mr. Bread',
      filling: 'ohne Füllung',
      topping: 'ohne Topping',
      price: 1.80,
      img: 'img/saltyDonuts/donut-salty4.jpg',
      category: ['salty-donut'],
    },
    {
      id: 13,
      name: 'Salted Apple-Cinnamon',
      filling: 'Apfel-Zimt-Füllung',
      topping: 'salzige Karamellglasur',
      price: 3.00,
      img: 'img/saltyDonuts/donut-salty5.jpg',
      category: ['salty-donut'],
    },
    {
      id: 14,
      name: 'Sweet-Box 1',
      filling: '2x Chocolate Frosted | 2x Oreo Dream | 2x Boston Créme ',
      topping: 'siehe Einzeldonut',
      price: 14.90,
      img: 'img/donutBox/donut-box1.jpg',
      category: ['donut-box', 'sweet-donut'],
    },
    {
      id: 15,
      name: 'Sweet-Box 2',
      filling: '2x Chocolate Frosted | 2x Fruit Explosion',
      topping: 'siehe Einzeldonut',
      price: 10.90,
      img: 'img/donutBox/donut-box2.jpg',
      category: ['donut-box', 'sweet-donut'],
    },
    {
      id: 16,
      name: 'Sweet-Box 3',
      filling: '9 Überraschungsdonuts',
      topping: 'siehe Einzeldonut',
      price: 24.90,
      img: 'img/donutBox/donut-box4.jpg',
      category: ['donut-box', 'sweet-donut'],
    },
    {
      id: 17,
      name: 'Salty-Box 1',
      filling: '3 Überraschungsdonuts',
      topping: 'siehe Einzeldonut',
      price: 7.90,
      img: 'img/donutBox/donut-box3.jpg',
      category: ['donut-box', 'salty-donut'],
    },
    {
      id: 18,
      name: 'Classic-Box',
      filling: '5x süße Donuts | 1x salziger Donut',
      topping: 'siehe Einzeldonut',
      price: 19.90,
      img: 'img/donutBox/donut-box5.jpg',
      category: ['donut-box','classic-donut'],
    },
  ]